### ISSUE TITLE
link to sbt shared plugin repository

### ISSUE THREAD

**Issue by kwark** [sbilinski/sbt-ecr#1]
Can you please link your excellent plugin to the shared sbt plugins repository on bintray?
This would make your sbt-ecr plugin more easily accessible for users behind a corporate Nexus/artifactory gateway.

Since you are already publishing on bintray, it is just a small effort.
Check the documentation for details: http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html#Linking+your+package+to+the+sbt+organization

**Comment by sbilinski** [comment]
Thanks for pointing this out! I've submitted a request to include this plugin in the community repository and will update the install instructions as soon as I get an approval.
