### ISSUE TITLE
Pushing to Region CN_North_1 doesn't work

### ISSUE THREAD

**Issue by phutflesz** [sbilinski/sbt-ecr#15]
I tried to automate an upload to AWS China (Region CN_North_1), however the domain
`def domain(region: Region, accountId: String) = s"${accountId}.dkr.ecr.${region}.amazonaws.com"`
doesn't take into account that AWS' domain in China is amazonaws.com.CN instead of only amazonaws.com.
The debug output from the AWS SDK displays the right URL during the build process:

INFORMATION: {ecr, cn-north-1} was not found in region metadata, trying to construct an endpoint using the standard pattern for this region: 'ecr.cn-north-1.amazonaws.com.cn'.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
Error response from daemon: Get https://************.dkr.ecr.cn-north-1.amazonaws.com/v2/: dial tcp: lookup ************.dkr.ecr.cn-north-1.amazonaws.com on 192.168.65.1:53: no such host

**Comment by sbilinski** [comment]
Thanks for reporting the issue @phutflesz. Would you like to contribute a fix for this or should I take care of it?

**Comment by sbilinski** [comment]
Thanks for the contribution @phutflesz! I've released the bug fix as `0.7.1`. Sorry about the delay.
